export const PERMISSIONS = [
  'clients.list',
  'clients.view',
  'clients.create',
  'clients.edit',
  'clients.archive',
  'clients.export',
  'clients.view_sensitive',
  'projects.view',
  'projects.sync',
  'projects.open_external',
  'projects.manage_links',
  'deliverables.view',
  'deliverables.plan',
  'deliverables.complete',
  'deliverables.reopen',
  'deliverables.cancel',
  'deliverables.adjust_target',
  'content.create',
  'content.review',
  'content.send_to_client',
  'content.approve_internal',
  'content.schedule',
  'content.publish',
  'content.delete',
  'financial.view_summary',
  'financial.view_details',
  'financial.edit',
  'financial.reconcile',
  'financial.export',
  'contracts.view',
  'contracts.create',
  'contracts.send',
  'contracts.resend',
  'contracts.cancel',
  'contracts.download',
  'commercial.view_pipeline',
  'commercial.edit_deal',
  'commercial.view_values',
  'commercial.export',
  'users.view',
  'users.invite',
  'users.edit_role',
  'users.edit_permissions',
  'users.assign_clients',
  'users.suspend',
  'users.remove',
  'teams.view',
  'teams.manage',
  'integrations.view',
  'integrations.connect',
  'integrations.reconnect',
  'integrations.sync',
  'integrations.remove',
  'admin.configure_organization',
  'admin.configure_metrics',
  'admin.configure_templates',
  'admin.view_audit',
  'admin.configure_retention'
] as const;

export type PermissionCode = typeof PERMISSIONS[number];

export function isValidPermissionCode(code: string): code is PermissionCode {
  return PERMISSIONS.includes(code as PermissionCode);
}
