import {
    Wallet, ShoppingCart, Car, Home, Pill, GraduationCap, Plane,
    Utensils, Gamepad2, Lightbulb, Wrench, Dog, Gift, CreditCard,
    TrendingUp, TrendingDown, Bus, Fuel, Baby, Shirt, Briefcase,
    Laptop, Smartphone, Banknote, Landmark, Dumbbell, Clapperboard,
    Beer, FileText, Scissors, Music, Heart, Star, Sun, Moon,
    Cloud, Umbrella, Key, Lock, MapPin, Phone, Mail, Camera,
    Headphones, Watch, Anchor, Coffee, Pizza, Bike,
    Zap, Wifi, Trophy, Truck, Trash, Timer, Ticket, Thermometer,
    Tablet, Sword, Stethoscope, Sofa, Snowflake, Skull, Signpost,
    Shield, Share2, Rocket, Repeat, Radio, Printer, Power,
    Plug, Play, PenTool, Palette, Package, Microscope, Mic,
    Megaphone, Medal, Map, LifeBuoy, Library, Layers, Globe,
    Ghost, Gavel, Gem, Frown, Frame, Flame, Flag, Fish,
    Fingerprint, Filter, Film, Feather, Eye, Eraser, Droplet,
    Download, DollarSign, Dna, Disc, Diamond, Database, Crown,
    Compass, Command, Code, CloudRain, Clock, Clipboard,
    CircleDollarSign, Cigarette, Church, Chrome, CheckCircle,
    Cat, Cast, Calculator, Calendar, Cake, Brush, Brain,
    Box, BookOpen, Bomb, Bluetooth, Bird, Bell, Beaker,
    Bath, Banana, Backpack, Axe, Award, Atom, Archive,
    Apple, Aperture, Leaf, Palmtree, Flower2
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, any> = {
    "Wallet": Wallet,
    "ShoppingCart": ShoppingCart,
    "Car": Car,
    "Home": Home,
    "Utensils": Utensils,
    "Plane": Plane,
    "Gamepad2": Gamepad2,
    "Pill": Pill,
    "Zap": Zap,
    "Wifi": Wifi,
    "Phone": Phone,
    "GraduationCap": GraduationCap,
    "Lightbulb": Lightbulb,
    "Wrench": Wrench,
    "Dog": Dog,
    "Cat": Cat,
    "Gift": Gift,
    "CreditCard": CreditCard,
    "TrendingUp": TrendingUp,
    "TrendingDown": TrendingDown,
    "Bus": Bus,
    "CheckCircle": CheckCircle,
    "Fuel": Fuel,
    "Baby": Baby,
    "Shirt": Shirt,
    "Briefcase": Briefcase,
    "Laptop": Laptop,
    "Smartphone": Smartphone,
    "Banknote": Banknote,
    "Landmark": Landmark,
    "Dumbbell": Dumbbell,
    "Clapperboard": Clapperboard,
    "Beer": Beer,
    "Coffee": Coffee,
    "Pizza": Pizza,
    "Bike": Bike,
    "FileText": FileText,
    "Scissors": Scissors,
    "Music": Music,
    "Heart": Heart,
    "Star": Star,
    "Sun": Sun,
    "Moon": Moon,
    "Cloud": Cloud,
    "Umbrella": Umbrella,
    "Key": Key,
    "Lock": Lock,
    "MapPin": MapPin,
    "Mail": Mail,
    "Camera": Camera,
    "Headphones": Headphones,
    "Watch": Watch,
    "Anchor": Anchor,
    "Trophy": Trophy,
    "Truck": Truck,
    "Trash": Trash,
    "Timer": Timer,
    "Ticket": Ticket,
    "Thermometer": Thermometer,
    "Tablet": Tablet,
    "Sword": Sword,
    "Stethoscope": Stethoscope,
    "Sofa": Sofa,
    "Snowflake": Snowflake,
    "Skull": Skull,
    "Signpost": Signpost,
    "Shield": Shield,
    "Share2": Share2,
    "Rocket": Rocket,
    "Repeat": Repeat,
    "Radio": Radio,
    "Printer": Printer,
    "Power": Power,
    "Plug": Plug,
    "Play": Play,
    "PenTool": PenTool,
    "Palette": Palette,
    "Package": Package,
    "Microscope": Microscope,
    "Mic": Mic,
    "Megaphone": Megaphone,
    "Medal": Medal,
    "Map": Map,
    "LifeBuoy": LifeBuoy,
    "Library": Library,
    "Layers": Layers,
    "Globe": Globe,
    "Ghost": Ghost,
    "Gavel": Gavel,
    "Gem": Gem,
    "Frown": Frown,
    "Frame": Frame,
    "Flame": Flame,
    "Flag": Flag,
    "Fish": Fish,
    "Fingerprint": Fingerprint,
    "Filter": Filter,
    "Film": Film,
    "Feather": Feather,
    "Eye": Eye,
    "Eraser": Eraser,
    "Droplet": Droplet,
    "Download": Download,
    "DollarSign": DollarSign,
    "Dna": Dna,
    "Disc": Disc,
    "Diamond": Diamond,
    "Database": Database,
    "Crown": Crown,
    "Compass": Compass,
    "Command": Command,
    "Code": Code,
    "CloudRain": CloudRain,
    "Clock": Clock,
    "Clipboard": Clipboard,
    "CircleDollarSign": CircleDollarSign,
    "Cigarette": Cigarette,
    "Church": Church,
    "Chrome": Chrome,
    "Cast": Cast,
    "Calculator": Calculator,
    "Calendar": Calendar,
    "Cake": Cake,
    "Brush": Brush,
    "Brain": Brain,
    "Box": Box,
    "BookOpen": BookOpen,
    "Bomb": Bomb,
    "Bluetooth": Bluetooth,
    "Bird": Bird,
    "Bell": Bell,
    "Beaker": Beaker,
    "Bath": Bath,
    "Banana": Banana,
    "Backpack": Backpack,
    "Axe": Axe,
    "Award": Award,
    "Atom": Atom,
    "Archive": Archive,
    "Apple": Apple,
    "Aperture": Aperture,
    "Leaf": Leaf,
    "Palmtree": Palmtree,
    "Flower2": Flower2,
};

// Default subset for initial view
export const INITIAL_ICONS = [
    "Wallet", "ShoppingCart", "Car", "Home", "Utensils",
    "Plane", "Gamepad2", "Pill", "GraduationCap", "Lightbulb",
    "Gift", "Briefcase", "Baby", "Shirt", "Smartphone",
    "Coffee", "Pizza", "Beer", "Dumbbell", "Music"
];
